Changed from getopts to getopt.

diff --git a/scripts/current-user b/scripts/current-user
--- a/scripts/current-user
+++ b/scripts/current-user
@@ -7,7 +7,10 @@
 ### VARIABLES ###
 #################
 
-SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
+# The name of this script, and the directory where it is located
+SCRIPT_NAME="$(basename $(readlink -f $0))"
+SCRIPT_DIR="$(dirname $(readlink -f $0))"
+
 
 #################
 ### FUNCTIONS ###
@@ -17,11 +20,12 @@ function print_usage(){
     printf "\nPrints the username of the current configuration used.
     
 Usage:
-    current -T -f
+    current [-f|--file-loc] [-h|--help] [-T|--testing] 
 
 Input Arguments:
-    -f      print the file location of the current configuration file too.
-    -T      Runs the script in a test mode by prepending all paths and setting the current user to test.
+    -f|--file-loc   Print the file location of the current configuration file too.
+    -h|--help       Prints this help menu.
+    -T|--testing    Runs the script in a test mode by prepending all paths and setting the current user to test.
 
 "
 }
@@ -37,12 +41,20 @@ source ${SCRIPT_DIR}/common
 # Parse Arguments
 TESTING=false
 PRINT_CONFIG_FILE_LOC=false
-while getopts fTh OPT; do
-    case "${OPT}" in
-        f) PRINT_CONFIG_FILE_LOC=true ;;
-        T) TESTING=true ;;
-        h) print_usage; exit ;;
-        ?) print_usage; exit ;;
+PARSED_ARGS=$(getopt -a -n ${SCRIPT_NAME} -o 'fT' --long 'file-loc,testing' -- "$@")
+eval set -- "${PARSED_ARGS}"
+while true; do
+    case "$1" in 
+        -f|--file-loc) PRINT_CONFIG_FILE_LOC=true; shift ;;
+        -h|--help) print_usage; exit 0 ;;
+        -T|--testing) TESTING=true; shift 1 ;;
+        # -- indicates end of arguments, break while loop
+        --) shift; break ;;
+        # invalid option was passed, print usage
+        *)
+        printf "${ERROR}Unrecognized option '$1'\n" 
+        print_usage 
+        exit 1 ;;    
     esac
 done
 
diff --git a/scripts/list b/scripts/list
--- a/scripts/list
+++ b/scripts/list
@@ -7,7 +7,9 @@
 ### VARIABLES ###
 #################
 
-SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
+# The name of this script, and the directory where it is located
+SCRIPT_NAME="$(basename $(readlink -f $0))"
+SCRIPT_DIR="$(dirname $(readlink -f $0))"
 
 #################
 ### FUNCTIONS ###
@@ -17,13 +19,14 @@ function print_usage(){
     printf "\nLists the common and user specific QCR ROS services for the given user, whether they are enabled/disabled, and their status.
     
 Usage:
-    list -u <service_user> -i -a -d
+    list [-h|--help] [-i|--ignore-qcr] [-a|--list-all] [-d|--list-disabled] [-u|--user <user>]
 
 Input Arguments:
-    -u <user>   The user services to list. Defaults to the current user.
-    -i          Ignore the common QCR services.
-    -a          List all system services.
-    -d          List disabled services. 
+    -a|--list-all       List all system services.
+    -d|--list-disabled  List disabled services. 
+    -i|--ignore-qcr     Ignore the common QCR services.
+    -h|--help           Show this help menu.
+    -u|--user <user>    The user services to list. Defaults to the current user.
 
 Examples:
     List all generic and user sepcific services for the current user: ./list
@@ -38,23 +41,36 @@ Examples:
 ### MAIN ###
 ############
 
+# Set shell options, enter help set in terminal for definitions
+set -o pipefail
+
 # Source common components
 source ${SCRIPT_DIR}/common
 
+
 # Parse Arguments
-IGN_COMMON_ROS_SRVS=false
+IGN_QCR_SRVS=false
 LIST_ALL_SRVS=false
 LIST_DISABLED_SRVS=false
-while getopts u:iadh OPT; do
-    case "${OPT}" in
-        u) SERVICE_USER=${OPTARG} ;;
-        i) IGN_COMMON_ROS_SRVS=true ;;
-        a) LIST_ALL_SRVS=true ;;
-        d) LIST_DISABLED_SRVS=true ;;
-        h) print_usage; exit ;;
-        ?) print_usage; exit ;;
+PARSED_ARGS=$(getopt -a -n ${SCRIPT_NAME} -o 'adihu:' --long 'list-all,list-disabled,ignore-qcr,help,user:' -- "$@")
+eval set -- "${PARSED_ARGS}"
+while true; do
+    case "$1" in 
+        -a|--list-all) LIST_ALL_SRVS=true; shift ;;
+        -d|--list-disabled) LIST_DISABLED_SRVS=true; shift ;;
+        -i|--ignore-qcr) IGN_QCR_SRVS=true; shift ;;
+        -h|--help) print_usage; exit 0 ;;
+        -u|--user) SERVICE_USER=$2; shift 2 ;;
+        # -- indicates end of arguments, break while loop
+        --) shift; break ;;
+        # invalid option was passed, print usage
+        *)
+        printf "${ERROR}Unrecognized option '$1'\n" 
+        print_usage 
+        exit 1 ;;    
     esac
 done
+
 
 # Get filenames of services to list
 if [ ${LIST_ALL_SRVS} == true ]; then
@@ -66,7 +82,7 @@ else
     
     # Prepend common QCR ROS services to array if required
     COMMON_ROS_SRVS=("${SERVICE_PATH}/ros.service" "${SERVICE_PATH}/roscore.service" "${SERVICE_PATH}/ros-watchdog.service" "${SERVICE_PATH}/robot-bringup.service" "${SERVICE_PATH}/qut-iaclient.service")
-    if [ ${IGN_COMMON_ROS_SRVS} == false ]; then
+    if [ ${IGN_QCR_SRVS} == false ]; then
         SERVICE_FILES=( "${COMMON_ROS_SRVS[@]}" "${SERVICE_FILES[@]}" )
     fi
 fi
diff --git a/scripts/new b/scripts/new
--- a/scripts/new
+++ b/scripts/new
@@ -7,7 +7,10 @@
 ### VARIABLES ###
 #################
 
-SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
+# The name of this script, and the directory where it is located
+SCRIPT_NAME="$(basename $(readlink -f $0))"
+SCRIPT_DIR="$(dirname $(readlink -f $0))"
+
 
 #################
 ### FUNCTIONS ###
@@ -17,12 +20,13 @@ function print_usage(){
     printf "\nCopies the default service configuration to the current user workspace.
     
 Usage:
-    new -T -f <config_file> -d <default_config_file>
+    new [-c|--config <file>] [-d|--default <cile>] [-h|--help] [-T|--testing]
 
 Input Arguments:
-    -f <config_file>            The location where the new config file is to be stored. Defaults to /home/<current-user>/.qcr/ros-service-config.yml
-    -d <default_config_file>    The location to where the default config file. Defaults to /etc/qcr/ros-service-config_default.yml
-    -T                          Runs the script in a test mode by prepending all paths and setting the current user to test.
+    -c|--config  <file>     The location where the new config file is to be stored. Defaults to /home/<current-user>/.qcr/ros-service-config.yml
+    -d|--default <file>     The location to where the default config file. Defaults to /etc/qcr/ros-service-config_default.yml
+    -h|--help               Shows this help menu.
+    -T|--testing            Runs the script in a test mode by prepending all paths and setting the current user to test.
 "
 }
 
@@ -31,19 +35,29 @@ Input Arguments:
 ### MAIN ### 
 ############
 
+# Set shell options, enter help set in terminal for definitions
+set -o pipefail
+
 # Source common components
 source ${SCRIPT_DIR}/common
 
 # Parse Arguments
 TESTING=false
-
-while getopts f:dTh OPT; do
-    case "${OPT}" in
-        f) CONFIG_FILE=${OPTARG} ;;
-        d) DEFAULT_CONFIG_FILE=${OPTARG} ;;
-        T) TESTING=true ;;
-        h) print_usage; exit ;;
-        ?) print_usage; exit ;;
+PARSED_ARGS=$(getopt -a -n ${SCRIPT_NAME} -o 'c:d:hT' --long 'default:,config:,help,testing' -- "$@")
+eval set -- "${PARSED_ARGS}"
+while true; do
+    case "$1" in 
+        -c|--config) CONFIG_FILE=$2; shift 2 ;;
+        -d|--default) DEFAULT_CONFIG_FILE=$2; shift 2 ;;
+        -h|--help) print_usage; exit 0 ;;
+        -T|--testing) TESTING=true; shift 1 ;;
+        # -- indicates end of arguments, break while loop
+        --) shift; break ;;
+        # invalid option was passed, print usage
+        *)
+        printf "${ERROR}Unrecognized option '$1'\n" 
+        print_usage 
+        exit 1 ;;    
     esac
 done
 
diff --git a/scripts/update b/scripts/update
--- a/scripts/update
+++ b/scripts/update
@@ -7,7 +7,10 @@
 ### VARIABLES ###
 #################
 
-SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
+# The name of this script, and the directory where it is located
+SCRIPT_NAME="$(basename $(readlink -f $0))"
+SCRIPT_DIR="$(dirname $(readlink -f $0))"
+
 
 
 #################
@@ -19,16 +22,17 @@ function print_usage(){
     whenever a services configuration file is updated.
     
 Usage:
-    update -T -c <command_file> -f <config_file> -s <config_file_symlink> -p <service_path> -u <service_user>
+    update [-C|--command <file>] [-c|--config <file>] [-h|--help] [-p|--path <path>] [-s|--symlink <file>] [-T|--testing] [-u|--user <user>]
 
 Input Arguments:
-    -c <command_file>           The file where generated commands should be stored. Defaults to /tmp/ros-service-commands
-    -f <config_file>            The config file to use for service configuration. Defaults to /home/<service_user>/.qcr/ros-service-config.yml. Providing this argument will set the config file path irrespective of the argument provided as the service_user.
-    -s <config_file_symlink>    The location where a symlink is created to store the currently used configuration file. Defaults to /etc/qcr/ros-service-config.yml
-    -p <service_path>           The path to where systemd service files are stored. Defaults to /etc/systemd/system
-    -u <service_user>           The username of the configuration file to be used. The username will also be added to each generated service. Defaults to the current user.
-    -T                          Runs the script in a test mode by prepending all paths and setting the current user to test. No changes to the system services will actually occur.
-
+    -C|--command  <file>    The file where generated commands should be stored. Defaults to /tmp/ros-service-commands
+    -c|--config   <file>    The config file to use for service configuration. Defaults to /home/<service_user>/.qcr/ros-service-config.yml. Providing this argument will set the config file path irrespective of the argument provided as the service_user.
+    -h|--help               Shows this help menu.
+    -p|--path     <path>    The path to where systemd service files are stored. Defaults to /etc/systemd/system
+    -s|--symlink  <file>    The location where a symlink is created to store the currently used configuration file. Defaults to /etc/qcr/ros-service-config.yml
+    -T|--testing            Runs the script in a test mode by prepending all paths and setting the current user to test. No changes to the system services will actually occur.
+    -u|--user     <user>    The username of the configuration file to be used. The username will also be added to each generated service. Defaults to the current user.
+    
 Example Usage:
     Use your service configuration: ./update
     Use the qcr user's service configuration: ./update -u qcr
@@ -57,17 +61,24 @@ source ${SCRIPT_DIR}/common
 # Parse Arguments
 TESTING=false
 CONFIG_FILE_PROVIDED=false
-
-while getopts c:f:S:P:p:u:Th OPT; do
-    case "${OPT}" in
-        c) COMMAND_FILE=${OPTARG} ;;
-        f) CONFIG_FILE=${OPTARG}; CONFIG_FILE_PROVIDED=true ;;
-        s) CONFIG_FILE_SYMLINK=${OPTARG} ;;
-        p) SERVICE_PATH=${OPTARG} ;;
-        u) SERVICE_USER=${OPTARG} ;;
-        T) TESTING=true ;;
-        h) print_usage; exit ;;
-        ?) print_usage; exit ;;
+PARSED_ARGS=$(getopt -a -n ${SCRIPT_NAME} -o 'c:d:hT' --long 'default:,config:,help,testing' -- "$@")
+eval set -- "${PARSED_ARGS}"
+while true; do
+    case "$1" in 
+        -C|--command) COMMAND_FILE=$2; shift 1 ;;
+        -c|--config) CONFIG_FILE=$2; CONFIG_FILE_PROVIDED=true; shift 2 ;;
+        -h|--help) print_usage; exit 0 ;;
+        -p|--path) SERVICE_PATH=$2; shift 2 ;;
+        -s|--symlink) CONFIG_FILE_SYMLINK=$2; shift 2 ;;
+        -T|--testing) TESTING=true; shift 1 ;;
+        -u|--user) SERVICE_USER=$2; shift 2 ;;
+        # -- indicates end of arguments, break while loop
+        --) shift; break ;;
+        # invalid option was passed, print usage
+        *)
+        printf "${ERROR}Unrecognized option '$1'\n" 
+        print_usage 
+        exit 1 ;;    
     esac
 done
 
diff --git a/services b/services
--- a/services
+++ b/services
@@ -10,8 +10,9 @@
 ### VARIABLES ###
 #################
 
-# Directory for this script
-SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
+# The name of this script, and the directory where it is located
+SCRIPT_NAME="$(basename $(readlink -f $0))"
+SCRIPT_DIR="$(dirname $(readlink -f $0))"
 
 
 #################
@@ -22,11 +23,13 @@ function print_usage(){
     printf "\nRuns the QCR Services tool.
     
 Usage:
-    services <command> <arguments>
+    services [-h|--help][-v|--verbose] <command> <arguments>
 
 Arguments:
-    <command>       the QCR service command to run.
-    <arguments>     the arguments for the QCR service command.
+    -h|--help       print this information to screen.
+    -v|--verbose    output additional info.
+    <command>       the command to run.
+    <arguments>     the arguments for command.
 
 Commands:
 " 
@@ -48,49 +51,65 @@ function get_commands(){
 ### MAIN ###
 ############
 
+# Set shell options, enter help set in terminal for definitions
+set -o pipefail
+
 # Source Common
 source ${SCRIPT_DIR}/scripts/common
 
 # Display heading
 display_heading "SERVICES TOOL"
 
-
-# Valid commands
-VALID_CMDS="$(get_commands)"
+# Split args into what is parsed here, and what goes to a subcommand
+SUB_INDEX=$(printf '%s\n' "$@" | grep -n '^[a-zA-Z]' | head -n 1 | cut -f1 -d: || echo "$(($#+1))")
+MAIN_ARGS=( "${@:1:$((SUB_INDEX-1))}")
+SUB_ARGS=( "${@:$SUB_INDEX}" )
 
 # Parse arguments
-while getopts h OPT; do
-    case "${OPT}" in
-        h|help) print_usage; exit ;;
-        ?) print_usage; exit ;;
+PARSED_ARGS=$(getopt -a -n ${SCRIPT_NAME} -o 'hv' --long 'help,verbose' -- "${MAIN_ARGS[@]}")
+eval set -- "${PARSED_ARGS}"
+VERBOSE=false
+while true; do
+    case "$1" in 
+        -h|--help) 
+        print_usage; exit 0;;
+        -v|--verbose) 
+        VERBOSE=true; shift ;;
+        # -- indicates end of arguments, break while loop
+        --) shift; break ;;
+        # invalid option was passed, print usage
+        *)
+        printf "${ERROR}Unrecognized option '$1'\n" 
+        print_usage 
+        exit 1 ;;    
     esac
 done
 
-# Valid number of arguments
-if [ $# -eq 0 ]; then
+# Valid number of sub arguments
+if [ ${#SUB_ARGS[@]} -eq 0 ]; then
     print_usage
     exit
 fi
 
-
 # Check command argument is valid
-ARGS=( "$@" )
-CMD=${ARGS[0]}
+VALID_CMDS="$(get_commands)"
+CMD=${SUB_ARGS[0]}
 if [[ ! " ${VALID_CMDS[*]} " =~ " ${CMD} "  ]]; then
     printf "${ERROR}The command ${YELLOW}${CMD}${RESET} does not exist.\n"
     print_usage
     exit
 fi
 
-# Get sub-script and arguments
-CMD=${ARGS[0]}
-ARGS_LIST=${ARGS[@]:1}
+# Get sub-script arguments
+ARGS_LIST=${SUB_ARGS[@]:1}
 
 # Print to terminal what is being called
-if [ ${#ARGS_LIST[@]} == 1 ] && [ "${ARGS_LIST[0]}" == "" ]; then
-    printf "${INFO}Calling '${YELLOW}${SCRIPT_DIR}/scripts/${CMD}${RESET}' with no arguments\n\n"
-else
-    printf "${INFO}Calling '${YELLOW}${SCRIPT_DIR}/scripts/${CMD}${RESET}' with arguments '${YELLOW}${ARGS[@]:1}${RESET}'\n\n"
+if [ ${VERBOSE} == true ]; then
+    if [ ${#ARGS_LIST[@]} == 1 ] && [ "${ARGS_LIST[0]}" == "" ]; then
+        printf "${INFO}Calling '${YELLOW}${SCRIPT_DIR}/scripts/${CMD}${RESET}' with no arguments\n\n"
+    else
+        printf "${INFO}Calling '${YELLOW}${SCRIPT_DIR}/scripts/${CMD}${RESET}' with arguments '${YELLOW}${ARGS[@]:1}${RESET}'\n\n"
+    fi
 fi
 
 # Run tool
